In [12]:
import numpy as np

from deepctr.models import DIN
from deepctr.feature_column import SparseFeat, VarLenSparseFeat, DenseFeat, get_feature_names

In [13]:
feature_columns = [SparseFeat('user', 3, embedding_dim=10), SparseFeat(
        'gender', 2, embedding_dim=4), SparseFeat('item_id', 3 + 1, embedding_dim=8),
                       SparseFeat('cate_id', 2 + 1, embedding_dim=4), DenseFeat('pay_score', 1)]

In [14]:
feature_columns

[SparseFeat(name='user', vocabulary_size=3, embedding_dim=10, use_hash=False, vocabulary_path=None, dtype='int32', embeddings_initializer=<tensorflow.python.keras.initializers.initializers_v1.RandomNormal object at 0x00000148FCAD40A0>, embedding_name='user', group_name='default_group', trainable=True),
 SparseFeat(name='gender', vocabulary_size=2, embedding_dim=4, use_hash=False, vocabulary_path=None, dtype='int32', embeddings_initializer=<tensorflow.python.keras.initializers.initializers_v1.RandomNormal object at 0x00000148FCAD40D0>, embedding_name='gender', group_name='default_group', trainable=True),
 SparseFeat(name='item_id', vocabulary_size=4, embedding_dim=8, use_hash=False, vocabulary_path=None, dtype='int32', embeddings_initializer=<tensorflow.python.keras.initializers.initializers_v1.RandomNormal object at 0x00000148FCAD4130>, embedding_name='item_id', group_name='default_group', trainable=True),
 SparseFeat(name='cate_id', vocabulary_size=3, embedding_dim=4, use_hash=False, 

In [15]:
feature_columns += [
    VarLenSparseFeat(SparseFeat('hist_item_id', vocabulary_size=3 + 1, embedding_dim=8, embedding_name='item_id'),
                     maxlen=4, length_name="seq_length"),
    VarLenSparseFeat(SparseFeat('hist_cate_id', 2 + 1, embedding_dim=4, embedding_name='cate_id'), maxlen=4,
                     length_name="seq_length")]

In [16]:
feature_columns

[SparseFeat(name='user', vocabulary_size=3, embedding_dim=10, use_hash=False, vocabulary_path=None, dtype='int32', embeddings_initializer=<tensorflow.python.keras.initializers.initializers_v1.RandomNormal object at 0x00000148FCAD40A0>, embedding_name='user', group_name='default_group', trainable=True),
 SparseFeat(name='gender', vocabulary_size=2, embedding_dim=4, use_hash=False, vocabulary_path=None, dtype='int32', embeddings_initializer=<tensorflow.python.keras.initializers.initializers_v1.RandomNormal object at 0x00000148FCAD40D0>, embedding_name='gender', group_name='default_group', trainable=True),
 SparseFeat(name='item_id', vocabulary_size=4, embedding_dim=8, use_hash=False, vocabulary_path=None, dtype='int32', embeddings_initializer=<tensorflow.python.keras.initializers.initializers_v1.RandomNormal object at 0x00000148FCAD4130>, embedding_name='item_id', group_name='default_group', trainable=True),
 SparseFeat(name='cate_id', vocabulary_size=3, embedding_dim=4, use_hash=False, 

In [17]:
# Notice: History behavior sequence feature name must start with "hist_".
behavior_feature_list = ["item_id", "cate_id"]
uid = np.array([0, 1, 2])
ugender = np.array([0, 1, 0])
iid = np.array([1, 2, 3])  # 0 is mask value
cate_id = np.array([1, 2, 2])  # 0 is mask value
pay_score = np.array([0.1, 0.2, 0.3])

hist_iid = np.array([[1, 2, 3, 0], [3, 2, 1, 0], [1, 2, 0, 0]])
hist_cate_id = np.array([[1, 2, 2, 0], [2, 2, 1, 0], [1, 2, 0, 0]])
seq_length = np.array([3, 3, 2])  # the actual length of the behavior sequence

In [27]:
behavior_feature_list

['item_id', 'cate_id']

In [28]:
hist_cate_id

array([[1, 2, 2, 0],
       [2, 2, 1, 0],
       [1, 2, 0, 0]])

In [29]:
seq_length

array([3, 3, 2])

In [30]:
feature_dict = {'user': uid, 'gender': ugender, 'item_id': iid, 'cate_id': cate_id,
                'hist_item_id': hist_iid, 'hist_cate_id': hist_cate_id,
                'pay_score': pay_score, 'seq_length': seq_length}

In [32]:
feature_dict

{'user': array([0, 1, 2]),
 'gender': array([0, 1, 0]),
 'item_id': array([1, 2, 3]),
 'cate_id': array([1, 2, 2]),
 'hist_item_id': array([[1, 2, 3, 0],
        [3, 2, 1, 0],
        [1, 2, 0, 0]]),
 'hist_cate_id': array([[1, 2, 2, 0],
        [2, 2, 1, 0],
        [1, 2, 0, 0]]),
 'pay_score': array([0.1, 0.2, 0.3]),
 'seq_length': array([3, 3, 2])}

In [35]:
x = {name: feature_dict[name] for name in get_feature_names(feature_columns)}
x

{'user': array([0, 1, 2]),
 'gender': array([0, 1, 0]),
 'item_id': array([1, 2, 3]),
 'cate_id': array([1, 2, 2]),
 'pay_score': array([0.1, 0.2, 0.3]),
 'hist_item_id': array([[1, 2, 3, 0],
        [3, 2, 1, 0],
        [1, 2, 0, 0]]),
 'seq_length': array([3, 3, 2]),
 'hist_cate_id': array([[1, 2, 2, 0],
        [2, 2, 1, 0],
        [1, 2, 0, 0]])}

In [37]:
y = np.array([1, 0, 1])
y

array([1, 0, 1])

In [38]:
behavior_feature_list

['item_id', 'cate_id']

In [39]:
x, y, feature_columns, behavior_feature_list

({'user': array([0, 1, 2]),
  'gender': array([0, 1, 0]),
  'item_id': array([1, 2, 3]),
  'cate_id': array([1, 2, 2]),
  'pay_score': array([0.1, 0.2, 0.3]),
  'hist_item_id': array([[1, 2, 3, 0],
         [3, 2, 1, 0],
         [1, 2, 0, 0]]),
  'seq_length': array([3, 3, 2]),
  'hist_cate_id': array([[1, 2, 2, 0],
         [2, 2, 1, 0],
         [1, 2, 0, 0]])},
 array([1, 0, 1]),
 [SparseFeat(name='user', vocabulary_size=3, embedding_dim=10, use_hash=False, vocabulary_path=None, dtype='int32', embeddings_initializer=<tensorflow.python.keras.initializers.initializers_v1.RandomNormal object at 0x00000148FCAD40A0>, embedding_name='user', group_name='default_group', trainable=True),
  SparseFeat(name='gender', vocabulary_size=2, embedding_dim=4, use_hash=False, vocabulary_path=None, dtype='int32', embeddings_initializer=<tensorflow.python.keras.initializers.initializers_v1.RandomNormal object at 0x00000148FCAD40D0>, embedding_name='gender', group_name='default_group', trainable=True),


In [40]:
model = DIN(feature_columns, behavior_feature_list)

In [41]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
item_id (InputLayer)            [(None, 1)]          0                                            
__________________________________________________________________________________________________
cate_id (InputLayer)            [(None, 1)]          0                                            
__________________________________________________________________________________________________
hist_item_id (InputLayer)       [(None, 4)]          0                                            
__________________________________________________________________________________________________
hist_cate_id (InputLayer)       [(None, 4)]          0                                            
______________________________________________________________________________________________

In [42]:
model.compile('adam', 'binary_crossentropy',
                  metrics=['binary_crossentropy'])

In [43]:
history = model.fit(x, y, verbose=1, epochs=10, validation_split=0.5)

Epoch 1/10
1/1 [==============================] - 2s 2s/step - loss: 0.6997 - binary_crossentropy: 0.6997 - val_loss: 0.6946 - val_binary_crossentropy: 0.6946
Epoch 2/10
1/1 [==============================] - 0s 28ms/step - loss: 0.6900 - binary_crossentropy: 0.6900 - val_loss: 0.6931 - val_binary_crossentropy: 0.6931
Epoch 3/10
1/1 [==============================] - 0s 30ms/step - loss: 0.6837 - binary_crossentropy: 0.6837 - val_loss: 0.6919 - val_binary_crossentropy: 0.6919
Epoch 4/10
1/1 [==============================] - 0s 30ms/step - loss: 0.6781 - binary_crossentropy: 0.6781 - val_loss: 0.6909 - val_binary_crossentropy: 0.6909
Epoch 5/10
1/1 [==============================] - 0s 31ms/step - loss: 0.6726 - binary_crossentropy: 0.6726 - val_loss: 0.6901 - val_binary_crossentropy: 0.6901
Epoch 6/10
1/1 [==============================] - 0s 30ms/step - loss: 0.6663 - binary_crossentropy: 0.6663 - val_loss: 0.6896 - val_binary_crossentropy: 0.6896
Epoch 7/10
1/1 [====================